env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended', 'plugin:@typescript-eslint/recommended']

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
  ecmaVersion: 9
  sourceType: module

plugins: ['@typescript-eslint', 'react']

settings:
  react:
    version: '17'

rules: {
  react/prop-types: off,
  # react/sort-comp: ['warning', {
  #   order: [
  #       'static-variables',
  #       'static-methods',
  #       'instance-variables',
  #       'lifecycle',
  #       'render',
  #       'everything-else'
  #   ]
  # }],
  quotes: [
    'error',
    'single'
  ],
  no-console: 'off',
  no-invalid-this: 0,
}
